### ISSUE TITLE
Mention Coordinates on Maven Central

### ISSUE THREAD

**Issue by kwin** [code-distillery/filevault-oak-reindex-hook#2]
That hook looks really helpful. To directly leverage that in other packages without duplicating any code it would be great if you could deploy that to Maven Central. That way one could integrate that via https://maven.apache.org/plugins/maven-dependency-plugin/copy-dependencies-mojo.html into the newly generated package (containing the index definitions).

**Comment by kwin** [comment]
Just figured out it is already there. Maybe you can mention that in the readme ;-)

**Comment by jsedding** [comment]
Thanks for the suggestion. I added the maven coordinates to the readme. Please have a look if it matches your expectations.

**Comment by kwin** [comment]
Perfect, thanks a lot.
